'use client'

import React, { useState } from 'react'
import { Link, Sparkles, Image, Type, Tag, FileText, Quote, Download, Copy, Check, Share2, History, Trash2, Clock, ChevronDown, ChevronUp } from 'lucide-react'
import { PosterData, HistoryRecord } from '@/types'

/**
 * 编辑器面板 Props
 */
interface EditorPanelProps {
  data: PosterData
  onChange: (data: Partial<PosterData>) => void
  onAnalyze: () => void
  onDownload: () => void
  isAnalyzing?: boolean
  autoGeneratedShareText?: string
  // 历史记录相关
  history?: HistoryRecord[]
  onLoadHistory?: (record: HistoryRecord) => void
  onDeleteHistory?: (id: string) => void
  onClearHistory?: () => void
}

/**
 * 表单输入框组件
 */
const FormInput: React.FC<{
  label: string
  icon: React.ReactNode
  value: string
  onChange: (value: string) => void
  placeholder?: string
  type?: 'text' | 'url'
}> = ({ label, icon, value, onChange, placeholder, type = 'text' }) => (
  <div className="space-y-2">
    <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
      {icon}
      {label}
    </label>
    <input
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm
                 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500
                 transition-all duration-200"
    />
  </div>
)

/**
 * 表单文本域组件
 */
const FormTextarea: React.FC<{
  label: string
  icon: React.ReactNode
  value: string
  onChange: (value: string) => void
  placeholder?: string
  rows?: number
}> = ({ label, icon, value, onChange, placeholder, rows = 3 }) => (
  <div className="space-y-2">
    <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
      {icon}
      {label}
    </label>
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      rows={rows}
      className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm
                 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500/20 
                 focus:border-blue-500 transition-all duration-200"
    />
  </div>
)

/**
 * 历史记录面板组件
 */
const HistoryPanel: React.FC<{
  history: HistoryRecord[]
  onLoad: (record: HistoryRecord) => void
  onDelete: (id: string) => void
  onClear: () => void
}> = ({ history, onLoad, onDelete, onClear }) => {
  const [isExpanded, setIsExpanded] = useState(false)

  // 格式化时间戳
  const formatTime = (timestamp: number) => {
    const date = new Date(timestamp)
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffMins = Math.floor(diffMs / (1000 * 60))
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60))
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))

    if (diffMins < 1) return '刚刚'
    if (diffMins < 60) return `${diffMins}分钟前`
    if (diffHours < 24) return `${diffHours}小时前`
    if (diffDays < 7) return `${diffDays}天前`
    
    return date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })
  }

  if (history.length === 0) {
    return null
  }

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      {/* 折叠标题 */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="w-full flex items-center justify-between px-4 py-3 bg-gray-50 
                   hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center gap-2 text-sm font-medium text-gray-700">
          <History size={16} className="text-gray-500" />
          历史记录
          <span className="px-1.5 py-0.5 bg-gray-200 text-gray-600 text-xs rounded-full">
            {history.length}
          </span>
        </div>
        {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
      </button>

      {/* 历史列表 */}
      {isExpanded && (
        <div className="max-h-64 overflow-y-auto">
          {history.map((record) => (
            <div
              key={record.id}
              className="flex items-center justify-between px-4 py-3 border-t border-gray-100
                         hover:bg-blue-50/50 transition-colors group"
            >
              {/* 记录信息 */}
              <button
                onClick={() => onLoad(record)}
                className="flex-1 text-left"
              >
                <p className="text-sm font-medium text-gray-800 truncate max-w-[180px]">
                  {record.data.title || '未命名'}
                </p>
                <p className="flex items-center gap-1 text-xs text-gray-400 mt-0.5">
                  <Clock size={12} />
                  {formatTime(record.timestamp)}
                </p>
              </button>

              {/* 删除按钮 */}
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  onDelete(record.id)
                }}
                className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 
                           rounded-md opacity-0 group-hover:opacity-100 transition-all"
                title="删除记录"
              >
                <Trash2 size={14} />
              </button>
            </div>
          ))}

          {/* 清空按钮 */}
          {history.length > 0 && (
            <button
              onClick={onClear}
              className="w-full px-4 py-2 text-xs text-gray-400 hover:text-red-500 
                         border-t border-gray-100 hover:bg-red-50/50 transition-colors"
            >
              清空所有记录
            </button>
          )}
        </div>
      )}
    </div>
  )
}

/**
 * 分享文案生成器组件
 */
const ShareTextGenerator: React.FC<{ data: PosterData; autoGeneratedText?: string }> = ({ data, autoGeneratedText }) => {
  const [shareText, setShareText] = useState('')
  const [isCopied, setIsCopied] = useState(false)
  const [isExpanded, setIsExpanded] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  // 当收到自动生成的文案时，自动显示
  React.useEffect(() => {
    console.log('ShareTextGenerator useEffect 触发, autoGeneratedText:', autoGeneratedText)
    if (autoGeneratedText && autoGeneratedText.trim()) {
      console.log('自动展开分享文案，isExpanded 将设置为 true')
      setShareText(autoGeneratedText)
      setIsExpanded(true)
      console.log('isExpanded 已设置, shareText:', autoGeneratedText.substring(0, 30) + '...')
    }
  }, [autoGeneratedText])

  /**
   * 生成分享文案
   */
  const generateShareText = async () => {
    if (!data.title || !data.description) {
      alert('请先生成海报内容')
      return
    }

    setIsGenerating(true)
    try {
      console.log('开始生成分享文案...')
      
      // 调用 API 生成分享文案
      const response = await fetch('/api/generate-share', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: data.title,
          description: data.description,
          tags: data.tags,
        }),
      })
      
      const result = await response.json()
      
      if (!response.ok || !result.success) {
        throw new Error(result.error || '生成失败')
      }
      
      console.log('AI 生成的分享文案:', result.shareText)
      console.log('分享文案长度:', result.shareText?.length || 0)
      
      // 组装最终文案（格式：固定开场白 → 🎬片名 → 🏷️标签 → 正文）
      const text = `各位大朋友、小朋友们，大家晚上好。欢迎大家来到【老约翰周末放映室】。

🎬 ${data.title}

🏷️ ${data.tags.join('，')}

${result.shareText}`

      console.log('最终文案长度:', text.length)
      setShareText(text)
      setIsExpanded(true)
      
    } catch (error) {
      console.error('生成分享文案失败:', error)
      alert(`生成失败：${error instanceof Error ? error.message : '请检查网络连接'}`)
    } finally {
      setIsGenerating(false)
    }
  }

  /**
   * 复制到剪贴板
   */
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(shareText)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 2000)
    } catch (error) {
      console.error('复制失败:', error)
      alert('复制失败，请手动复制')
    }
  }

  return (
    <div className="space-y-3">
      {/* 生成按钮 */}
      <button
        onClick={generateShareText}
        disabled={!data.title || !data.description || isGenerating}
        className="w-full flex items-center justify-center gap-2 px-4 py-2.5 
                   bg-gray-200 text-gray-700 rounded-xl font-medium text-sm
                   hover:bg-gray-300 active:scale-[0.98]
                   disabled:opacity-40 disabled:cursor-not-allowed
                   transition-all duration-200"
      >
        <Share2 size={16} />
        {isGenerating ? 'AI 生成中...' : (shareText ? '重新生成文案' : '生成分享文案')}
      </button>

      {/* 文案显示区域 */}
      {isExpanded && shareText && (
        <div className="relative">
          <div className="bg-gradient-to-br from-purple-50 to-pink-50 border border-purple-200 rounded-lg p-4">
            <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans">
              {shareText}
            </pre>
          </div>
          
          {/* 复制按钮 */}
          <button
            onClick={copyToClipboard}
            className="absolute top-2 right-2 flex items-center gap-1 px-3 py-1.5 
                       bg-white/90 backdrop-blur-sm border border-purple-300 
                       rounded-md text-xs font-medium text-purple-600
                       hover:bg-purple-50 transition-colors"
          >
            {isCopied ? (
              <>
                <Check size={14} />
                已复制
              </>
            ) : (
              <>
                <Copy size={14} />
                复制
              </>
            )}
          </button>
        </div>
      )}
    </div>
  )
}

/**
 * 编辑器面板组件
 * 提供表单控件用于编辑海报数据
 */
const EditorPanel: React.FC<EditorPanelProps> = ({
  data,
  onChange,
  onAnalyze,
  onDownload,
  isAnalyzing = false,
  autoGeneratedShareText,
  history = [],
  onLoadHistory,
  onDeleteHistory,
  onClearHistory,
}) => {
  // 复制状态
  const [copied, setCopied] = useState(false)

  /**
   * 处理标签输入变化
   * 将逗号分隔的字符串转换为数组
   */
  const handleTagsChange = (value: string) => {
    const tags = value.split(/[,，]/).map(tag => tag.trim()).filter(Boolean)
    onChange({ tags })
  }

  /**
   * 处理封面图上传
   */
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = (event) => {
        onChange({ coverImage: event.target?.result as string })
      }
      reader.readAsDataURL(file)
    }
  }

  /**
   * 生成社群分享文案
   */
  const generateShareText = (): string => {
    const emoji = '🎬'
    const separator = '\n━━━━━━━━━━━\n'
    
    let shareText = `${emoji} ${data.title || '精彩动画短片'}\n`
    
    // 添加标签
    if (data.tags && data.tags.length > 0) {
      shareText += `\n🏷️ ${data.tags.join(' · ')}\n`
    }
    
    shareText += separator
    
    // 添加简介
    if (data.description) {
      shareText += `📖 ${data.description}\n`
    }
    
    shareText += separator
    
    // 添加推荐语
    if (data.recommendation) {
      shareText += `💬 ${data.recommendation}\n`
    }
    
    shareText += separator
    
    // 添加链接
    if (data.videoUrl) {
      shareText += `🔗 观看链接：\n${data.videoUrl}\n`
    }
    
    shareText += `\n✨ ${data.brandName || '周末放映室'} · 精选优质儿童动画短片`
    
    return shareText
  }

  /**
   * 复制分享文案到剪贴板
   */
  const handleCopyShareText = async () => {
    try {
      const shareText = generateShareText()
      await navigator.clipboard.writeText(shareText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      console.error('复制失败:', error)
      alert('复制失败，请重试')
    }
  }

  return (
    <div className="h-full flex flex-col bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      {/* 面板标题 */}
      <div className="px-6 py-4 border-b border-gray-100">
        <h2 className="text-lg font-semibold text-gray-800">海报编辑器</h2>
        <p className="text-sm text-gray-500 mt-1">输入视频链接，AI 帮你生成精美文案</p>
      </div>

      {/* 表单内容区 - 可滚动 */}
      <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5">
        {/* 视频链接输入 */}
        <FormInput
          label="视频链接"
          icon={<Link size={16} className="text-gray-400" />}
          value={data.videoUrl}
          onChange={(value) => onChange({ videoUrl: value, qrCodeUrl: value })}
          placeholder="粘贴 B站、YouTube 等视频链接"
          type="url"
        />

        {/* AI 智能分析按钮 */}
        <button
          onClick={onAnalyze}
          disabled={isAnalyzing || !data.videoUrl}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 
                     text-white rounded-xl font-medium text-sm
                     hover:opacity-90 active:scale-[0.98]
                     disabled:opacity-40 disabled:cursor-not-allowed
                     transition-all duration-200 shadow-sm"
          style={{ backgroundColor: '#2d4a78' }}
        >
          <Sparkles size={18} />
          {isAnalyzing ? '正在分析中...' : 'AI 智能分析'}
        </button>

        {/* 分隔线 */}
        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-gray-200"></div>
          </div>
          <div className="relative flex justify-center text-sm">
            <span className="px-3 bg-white text-gray-400">手动编辑</span>
          </div>
        </div>

        {/* 封面图上传 */}
        <div className="space-y-2">
          <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
            <Image size={16} className="text-gray-400" />
            封面图片
          </label>
          <div className="relative">
            <input
              type="file"
              accept="image/*"
              onChange={handleImageUpload}
              className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
            />
            <div className="flex items-center justify-center gap-2 px-4 py-3 border-2 border-dashed 
                            border-gray-200 rounded-lg text-gray-500 text-sm
                            hover:border-blue-400 hover:text-blue-500 transition-colors">
              <Image size={18} />
              点击上传封面图片
            </div>
          </div>
          {data.coverImage && data.coverImage !== '/mock-cover.jpg' && (
            <p className="text-xs text-green-600">✓ 已上传封面图</p>
          )}
        </div>

        {/* 标题输入 */}
        <FormInput
          label="视频标题"
          icon={<Type size={16} className="text-gray-400" />}
          value={data.title}
          onChange={(value) => onChange({ title: value })}
          placeholder="输入视频标题"
        />

        {/* 标签输入 */}
        <FormInput
          label="标签（逗号分隔）"
          icon={<Tag size={16} className="text-gray-400" />}
          value={data.tags.join('，')}
          onChange={handleTagsChange}
          placeholder="如：国外动画，奥斯卡获奖"
        />

        {/* 视频简介 */}
        <FormTextarea
          label="视频简介"
          icon={<FileText size={16} className="text-gray-400" />}
          value={data.description}
          onChange={(value) => onChange({ description: value })}
          placeholder="简要描述视频内容，约 60 字"
          rows={3}
        />

        {/* 推荐理由 */}
        <FormTextarea
          label="推荐理由"
          icon={<Quote size={16} className="text-gray-400" />}
          value={data.recommendation}
          onChange={(value) => onChange({ recommendation: value })}
          placeholder="写一段走心的推荐语，约 50 字"
          rows={4}
        />

        {/* 分享文案生成 */}
        <ShareTextGenerator data={data} autoGeneratedText={autoGeneratedShareText} />

        {/* 历史记录 */}
        {history.length > 0 && onLoadHistory && onDeleteHistory && onClearHistory && (
          <HistoryPanel
            history={history}
            onLoad={onLoadHistory}
            onDelete={onDeleteHistory}
            onClear={onClearHistory}
          />
        )}
      </div>

      {/* 底部下载按钮 */}
      <div className="px-6 py-4 border-t border-gray-100 bg-gray-50">
        <button
          onClick={onDownload}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 
                     text-white rounded-xl font-medium text-sm
                     hover:opacity-90 active:scale-[0.98]
                     transition-all duration-200"
          style={{ backgroundColor: '#2d4a78' }}
        >
          <Download size={18} />
          下载海报
        </button>
      </div>
    </div>
  )
}

export default EditorPanel
